### PR TITLE
15 Schema Generators

### LINKED ISSUE #15: Add Generator for User, UserKey, UserToken, & UserProfile
With discoverable credentials, username and email data is not required up front. And, schemas for UserKey, UserToken, and UserProfile may differ in surprising ways from traditional applications.

So, custom generators may helpful for developers implementing Passkey support **for the first time**.

## Acceptance Criteria

- [x] Must interpolate app and module names
- [x] Must generate `Users` **context**
- [x] Must generate `User` schema
- [x] Must generate `UserKeys` **context**
- [x] Must generate `UserKey` schema
- [x] Must generate `UserTokens` **context**
- [x] Must generate `UserToken` schema
- [ ] Must generate context tests
- [ ] Must document considerations and customizations

## Bonus

- [ ] If user schema already exists, prompt for appropriate action
  - For now, it may be wise to only allow the generator to run when there is no existing auth code.

### PR DESCRIPTION
**Pull request by type1fool**
# Overview

Resolves #15

This PR adds a new `wac.install` Mix Task for scaffolding schemas, migrations, and contexts for `WebauthnComponents`. 

## Changes

- First change
- Second change

## Tests

**TODO: ADD TEST GENERATOR**

```elixir
__TEST_OUTPUT__
```

## Collaborators

1. @type1fool
1. **more_collabs**

### CODE REVIEW

**Comment by jc00ke** [comment]
Hi there, thanks for working on this!

One question that comes to mind is why ULID? I used them in a project and actually moved away because there was a lot of friction when trying to query the database using a ULID (maybe I made the mistake of storing them as UUID datatype in Postgres.)

**Comment by type1fool** [comment]
> Hi there, thanks for working on this!
> 
> One question that comes to mind is why ULID? I used them in a project and actually moved away because there was a lot of friction when trying to query the database using a ULID (maybe I made the mistake of storing them as UUID datatype in Postgres.)

Hey @jc00ke! Thank you for checking out the PR.

Before I discovered [Ecto.ULID](https://github.com/TheRealReal/ecto-ulid), I had used UUIDs in my projects, primarily v4. The Shopify Engineering blog has [an article](https://shopify.engineering/building-resilient-payment-systems) about some of their optimizations, and that's where I learned about ULIDs.

> ULID is binary-compatible with UUID, so it can be stored in a uuid column in a database.
> https://github.com/TheRealReal/ecto-ulid

What problems surfaced when you used ULIDs?

**Comment by jc00ke** [comment]
The main issue was of ergonomics. Maybe storing the ULID as a UUID was a bad idea, but if I wanted to take

```elixir
%User{id: "some-ulid"}
```

and use it in

```sql
select * from users where id = 'some-ulid`;
```

I'd first have to convert it to an actual UUID, and that became laborious.

It sounds like UUID v7 will adopt the strengths of ULID and do away with the shortcomings of UUID v4 (mainly that v7 will use some amount of sequential information for better data locality) while being compatible textually too, so that you don't have to convert from ULID to UUID to use in SQL scripts.

And of course, these are generators, so it's not like I couldn't use them and then just change it myself... that's reasonable too! Or maybe it's an option, where the default is UUID v4.

**Comment by type1fool** [comment]
I see. It's been a couple years since I regularly wrote raw SQL, but I see how that would be problematic. In a project where the migration uses `:binary_id` instead of `:uuid`, I confirmed the behavior was the same.

[Ecto.UUID](https://hexdocs.pm/ecto/Ecto.UUID.html#generate/0) appears to implement only v4. [UUIDv7](https://hexdocs.pm/uuidv7/UUIDv7.html) looks promising, but it seems to be experimental. For now, I'm inclined to leave ULIDs in place and encourage users to make changes if needed.

Later, it should be fairly easy to accept a cli flag to set the preferred id type (ulid, uuidv4, uuidv7, int, etc).

**Comment by jc00ke** [comment]
Sounds good. I can't remember what library I was looking at, but it depended on http://github.com/bitwalker/uniq which supports v7. We're lucky we have good options!

**Comment by jc00ke** [comment]
Hmm, maybe v7 won't address my issue until Postgres natively supports it (which I believe there's a patch out there already)...

> As mentioned in the callout above, version 7 UUIDs are binary-compatible with ULIDs. This means you can encode a version 7 UUID using Crockford’s Base 32 algorithm and it will be a valid ULID, timestamp and all.

From https://uuid.ramsey.dev/en/stable/rfc4122/version7.html#convert-a-version-7-uuid-to-a-ulid

**Comment by type1fool** [comment]
@jc00ke Thank you again for the feedback!

**Pull request merged**
